### ISSUE TITLE
[Risk Framework]: Create New Staking OP Rewards group (Optimism)

### ISSUE THREAD

**Issue by rareweasel** [yearn/ydaemon#267]
{
"$schema": "risks",
"label": "Staking OP Rewards",
"codeReviewScore": 4,
"testingScore": 4,
"auditScore": 5,
"protocolSafetyScore": 3,
"complexityScore": 3,
"teamKnowledgeScore": 3,
"criteria": {
"nameLike": ["StakingRewards"],
"strategies": [],
"exclude": []
}
}

All the contracts added into this [registry](https://optimistic.etherscan.io/address/0xb54d1833aca99b0e50dfcc7f55a9165c6805bb9f) should be considered in this group. Check `addStakingPool` function.

More info in [this](https://github.com/yearn/yearn-infra/issues/50) issue.

**Comment by 0xBasically** [comment]
finished with https://github.com/yearn/ydaemon/pull/268
